spring:
  profiles:
    active: test
  mvc:
    log-request-details: true
server:
  port: 1337

logging:
  level:
    web: debug
    org:
      springframework:
        security: debug
    root: debug

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem

