spring:
  mvc:
    log-request-details: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${db_user_name}
    password: ${db_password}
    url: ${db_url}

server:
  port: 1337
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password
    key-alias: myapp

logging:
  level:
    web: debug
    org:
      springframework:
        security: debug
    root: debug

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem

